# IT Support Portal Services
#  docker network create it_support --subnet 10.3.0.0/24 -o com.docker.network.bridge.name=it0

networks:
  default:
    external: true
    name: it_support

services:
  redis:
    container_name: redis
    image: docker.io/bitnami/redis:7.4
    volumes:
      - "redis_data:/bitnami/redis/data"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  postgresql:
    container_name: postgresql
    restart: unless-stopped
    image: docker.io/bitnami/postgresql:16
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

volumes:
  redis_data:
  postgresql_data: