"""fix relations

Revision ID: 156b8b830b56
Revises: 635eb754ef6f
Create Date: 2025-09-09 13:37:11.371015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156b8b830b56'
down_revision: Union[str, Sequence[str], None] = '635eb754ef6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'department', 'employee', ['direction_manager_upn'], ['user_principal_name'], use_alter=True)
    op.create_foreign_key(None, 'department', 'employee', ['manager_upn'], ['user_principal_name'], use_alter=True)
    op.create_foreign_key(None, 'department', 'department', ['parent_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_constraint(None, 'department', type_='foreignkey')
    # ### end Alembic commands ###
