"""rename dhcp statistics index

Revision ID: 3d179b9c1ee7
Revises: a5f7086b368a
Create Date: 2025-10-30 19:45:43.027787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d179b9c1ee7'
down_revision: Union[str, Sequence[str], None] = 'a5f7086b368a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
