"""change call_number type in table employee

Revision ID: 498301353049
Revises: 5f6885c6475d
Create Date: 2025-09-18 12:37:20.733604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498301353049'
down_revision: Union[str, Sequence[str], None] = '5f6885c6475d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'call_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'call_number',
               existing_type=sa.String(length=25),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
