"""add table avaya_cdr

Revision ID: 5f6885c6475d
Revises: f3961ba7cbf4
Create Date: 2025-09-18 10:58:06.804013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6885c6475d'
down_revision: Union[str, Sequence[str], None] = 'f3961ba7cbf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaya_cdr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('calling_number', sa.String(length=25), nullable=False),
    sa.Column('called_number', sa.String(length=25), nullable=False),
    sa.Column('call_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaya_cdr')
    # ### end Alembic commands ###
