"""initial schemas

Revision ID: 635eb754ef6f
Revises: 
Create Date: 2025-09-09 11:50:19.791752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635eb754ef6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_user_email'), 'core_user', ['email'], unique=True)
    op.create_index(op.f('ix_core_user_id'), 'core_user', ['id'], unique=False)
    op.create_index(op.f('ix_core_user_username'), 'core_user', ['username'], unique=True)
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('manager_upn', sa.String(length=40), nullable=True),
    sa.Column('direction_manager_upn', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['direction_manager_upn'], ['employee.user_principal_name'], use_alter=True),
    sa.ForeignKeyConstraint(['manager_upn'], ['employee.user_principal_name'], use_alter=True),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_parent_id'), 'department', ['parent_id'], unique=False)
    op.create_table('pacs_access_point',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('pacs_card_owner',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('secondname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('user_principal_name', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('user_principal_name')
    )
    op.create_index(op.f('ix_employee_call_number'), 'employee', ['call_number'], unique=False)
    op.create_index(op.f('ix_employee_display_name'), 'employee', ['display_name'], unique=False)
    op.create_table('pacs_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('ap_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ap_id'], ['pacs_access_point.system_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['pacs_card_owner.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacs_event_ap_id'), 'pacs_event', ['ap_id'], unique=False)
    op.create_index(op.f('ix_pacs_event_created'), 'pacs_event', ['created'], unique=False)
    op.create_index(op.f('ix_pacs_event_owner_id'), 'pacs_event', ['owner_id'], unique=False)
    op.create_table('employee_card',
    sa.Column('employee_upn', sa.String(length=40), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['pacs_card_owner.system_id'], ),
    sa.ForeignKeyConstraint(['employee_upn'], ['employee.user_principal_name'], ),
    sa.PrimaryKeyConstraint('employee_upn', 'card_id')
    )
    op.create_table('employee_photo',
    sa.Column('user_principal_name', sa.String(length=40), nullable=False),
    sa.Column('thumbnail_photo', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_principal_name'], ['employee.user_principal_name'], ),
    sa.PrimaryKeyConstraint('user_principal_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_photo')
    op.drop_table('employee_card')
    op.drop_index(op.f('ix_pacs_event_owner_id'), table_name='pacs_event')
    op.drop_index(op.f('ix_pacs_event_created'), table_name='pacs_event')
    op.drop_index(op.f('ix_pacs_event_ap_id'), table_name='pacs_event')
    op.drop_table('pacs_event')
    op.drop_index(op.f('ix_employee_display_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_call_number'), table_name='employee')
    op.drop_table('employee')
    op.drop_table('position')
    op.drop_table('pacs_card_owner')
    op.drop_table('pacs_access_point')
    op.drop_index(op.f('ix_department_parent_id'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_core_user_username'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_id'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_email'), table_name='core_user')
    op.drop_table('core_user')
    # ### end Alembic commands ###
