"""add reserved field in dhcp statistics table

Revision ID: 8053f8535afa
Revises: 3d179b9c1ee7
Create Date: 2025-10-31 11:38:44.962948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8053f8535afa'
down_revision: Union[str, Sequence[str], None] = '3d179b9c1ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dhcp_scope_statistics', sa.Column('reserved', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dhcp_scope_statistics', 'reserved')
    # ### end Alembic commands ###
