"""change dhcp_scope_statistics table name

Revision ID: a5f7086b368a
Revises: 1cbf89d7c0ca
Create Date: 2025-10-30 16:45:05.760768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5f7086b368a'
down_revision: Union[str, Sequence[str], None] = '1cbf89d7c0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dhcp_scope_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dhcp_scope_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_addresses', sa.Integer(), nullable=False),
    sa.Column('in_use', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('pending_offers', sa.Integer(), nullable=False),
    sa.Column('percentage_in_use', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['dhcp_scope_id'], ['dhcp_scope.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dhcp_scope_statistics_collected', 'dhcp_scope_statistics', ['dhcp_scope_id', 'collected_at'], unique=False)
    op.drop_index(op.f('ix_dhcp_stat_scope_collected'), table_name='dhcp_scope_statistic')
    op.drop_table('dhcp_scope_statistic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dhcp_scope_statistic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dhcp_scope_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('total_addresses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('in_use', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pending_offers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('percentage_in_use', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dhcp_scope_id'], ['dhcp_scope.id'], name=op.f('dhcp_scope_statistic_dhcp_scope_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dhcp_scope_statistic_pkey'))
    )
    op.create_index(op.f('ix_dhcp_scope_statistics_collected'), 'dhcp_scope_statistic', ['dhcp_scope_id', 'collected_at'], unique=False)
    op.drop_index('ix_dhcp_scope_statistics_collected', table_name='dhcp_scope_statistics')
    op.drop_table('dhcp_scope_statistics')
    # ### end Alembic commands ###
