"""initial migration

Revision ID: c16baf01b4db
Revises: 
Create Date: 2025-09-06 17:45:23.040671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16baf01b4db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_user_email'), 'core_user', ['email'], unique=True)
    op.create_index(op.f('ix_core_user_id'), 'core_user', ['id'], unique=False)
    op.create_index(op.f('ix_core_user_username'), 'core_user', ['username'], unique=True)
    op.create_table('pacs_access_point',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('pacs_card_owner',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('secondname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('pacs_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('ap_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('card', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ap_id'], ['pacs_access_point.system_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['pacs_card_owner.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacs_event_ap_id'), 'pacs_event', ['ap_id'], unique=False)
    op.create_index(op.f('ix_pacs_event_created'), 'pacs_event', ['created'], unique=False)
    op.create_index(op.f('ix_pacs_event_owner_id'), 'pacs_event', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pacs_event_owner_id'), table_name='pacs_event')
    op.drop_index(op.f('ix_pacs_event_created'), table_name='pacs_event')
    op.drop_index(op.f('ix_pacs_event_ap_id'), table_name='pacs_event')
    op.drop_table('pacs_event')
    op.drop_table('pacs_card_owner')
    op.drop_table('pacs_access_point')
    op.drop_index(op.f('ix_core_user_username'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_id'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_email'), table_name='core_user')
    op.drop_table('core_user')
    # ### end Alembic commands ###
