"""add cisco vpn event

Revision ID: f3961ba7cbf4
Revises: 25026ff5f4a4
Create Date: 2025-09-16 15:16:38.792875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3961ba7cbf4'
down_revision: Union[str, Sequence[str], None] = '25026ff5f4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cisco_vpn_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('host', sa.String(length=12), nullable=True),
    sa.Column('event', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cisco_vpn_event')
    # ### end Alembic commands ###
