# Generated by Django 5.1.2 on 2024-11-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('system_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CardOwner',
            fields=[
                ('system_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('user_principal_name', models.CharField(max_length=250, null=True)),
                ('display_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('ap_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('card', models.IntegerField()),
                ('code', models.IntegerField()),
            ],
        ),
    ]
