# Generated by Django 5.1.2 on 2024-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardowner',
            old_name='user_principal_name',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='cardowner',
            name='display_name',
        ),
        migrations.AddField(
            model_name='cardowner',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cardowner',
            name='secondname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
