# Generated by Django 5.1.1 on 2024-10-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PacsAccessPoint',
            new_name='AccessPoint',
        ),
    ]
