# Generated by Django 5.1.1 on 2024-10-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacs', '0002_rename_pacsaccesspoint_accesspoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.IntegerField(default=0)),
                ('user_principal_name', models.CharField(max_length=250)),
                ('display_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('ap_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('card', models.IntegerField()),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='accesspoint',
            old_name='ap_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='system_id',
            field=models.IntegerField(default=0),
        ),
    ]
