# Generated by Django 5.1.2 on 2024-11-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacs', '0002_rename_user_principal_name_cardowner_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ap_id',
            field=models.ForeignKey(db_column='ap_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='pacs.accesspoint'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='pacs.cardowner'),
        ),
    ]
