# Generated by Django 5.1.1 on 2024-10-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacs', '0003_cardowner_event_rename_ap_name_accesspoint_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cardowner',
            name='id',
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='system_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cardowner',
            name='system_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ap_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pacs.accesspoint'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pacs.cardowner'),
        ),
    ]
