# Generated by Django 5.1.1 on 2024-10-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacs', '0004_remove_accesspoint_id_remove_cardowner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardowner',
            name='user_principal_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
