# Generated by Django 5.1.1 on 2024-10-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacs', '0005_alter_cardowner_user_principal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ap_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacs.accesspoint'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacs.cardowner'),
        ),
    ]
