"""initial

Revision ID: 1b6d1df299ab
Revises: 
Create Date: 2025-09-03 20:48:50.575389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6d1df299ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacs_access_point',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('pacs_card_owner',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('secondname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('pacs_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('ap_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('card', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ap_id'], ['pacs_access_point.system_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['pacs_card_owner.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacs_event')
    op.drop_table('pacs_card_owner')
    op.drop_table('pacs_access_point')
    # ### end Alembic commands ###
