# docker network create it_support --subnet 10.3.0.0/24 -o com.docker.network.bridge.name=it0
# docker network create -d macvlan --subnet=172.30.4.128/27 --gateway=172.30.4.129 --ip-range=172.30.4.128/27 -o parent=eth0 eth0

# docker network create -d ipvlan --subnet=172.30.4.192/27 --gateway=172.30.4.193 -o parent=eth0 -o ipvlan_mode=l2 it_ipvlan
# sudo ip link add it_macvlan link eth0 type macvlan mode bridge
# sudo ip addr add 172.30.4.145/27 dev it_macvlan
# sudo ifconfig it_macvlan up

networks:
  default:
    external: true
    name: it_support
  #it_ipvlan:
  #  external: true
  #  name: it_ipvlan

services:
  backend:
    container_name: backend
    build: .
    volumes:
      - ../..:/opt/project:cached
    #ports:
    #  - "8000:8000"
    #  - "31415:31415"
    #networks:
    #  it_ipvlan:
    #    ipv4_address: 172.20.4.222
  redis:
    container_name: redis
    image: docker.io/bitnami/redis:7.4
    volumes:
      - "redis_data:/bitnami/redis/data"
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    environment:
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
  postgresql:
    container_name: postgresql
    restart: unless-stopped
    image: docker.io/bitnami/postgresql:16
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  redis_data:
  postgresql_data: