import asyncio

from psycopg.sql import NULL
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.exc import IntegrityError
from db.database import engine, Base, AsyncSessionLocal
from models.employee import Position, Department, Employee, EmployeeCard  # ← Замените на путь к вашим моделям

# Данные для импорта
POSITIONS_DATA = [
    {"id": 0, "name": "Не задан"},
    {"id": 1, "name": "бухгалтер"},
    {"id": 2, "name": "ведущий бухгалтер"},
    {"id": 3, "name": "ведущий дизайнер"},
    {"id": 4, "name": "ведущий инженер"},
    {"id": 5, "name": "ведущий менеджер"},
    {"id": 6, "name": "ведущий специалист"},
    {"id": 7, "name": "ведущий экономист"},
    {"id": 8, "name": "ведущий юрисконсульт"},
    {"id": 9, "name": "водитель"},
    {"id": 10, "name": "Генеральный директор"},
    {"id": 11, "name": "главный бухгалтер"},
    {"id": 12, "name": "главный научный консультант"},
    {"id": 13, "name": "главный специалист"},
    {"id": 14, "name": "дежурный"},
    {"id": 15, "name": "директор филиала"},
    {"id": 16, "name": "заместитель Генерального директора"},
    {"id": 17, "name": "заместитель Генерального директора по финансам и экономике"},
    {"id": 18, "name": "заместитель главного бухгалтера"},
    {"id": 19, "name": "заместитель директора филиала"},
    {"id": 20, "name": "заместитель начальника отдела"},
    {"id": 21, "name": "заместитель начальника Управления"},
    {"id": 22, "name": "инженер"},
    {"id": 23, "name": "инженер-лаборант"},
    {"id": 24, "name": "менеджер"},
    {"id": 25, "name": "начальник группы"},
    {"id": 26, "name": "начальник отдела"},
    {"id": 27, "name": "начальник сектора"},
    {"id": 28, "name": "начальник Управления"},
    {"id": 29, "name": "секретарь-референт"},
    {"id": 30, "name": "советник Генерального директора"},
    {"id": 31, "name": "специалист"},
    {"id": 32, "name": "старший менеджер"},
]

DEPARTMENTS_DATA = [
    {"id": 0, "name": "Не задан", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 1, "name": "Руководство", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 2, "name": "Архив", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 3, "name": "Управление по работе с персоналом", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 4, "name": "Юридический отдел", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 5, "name": "Отдел лицензирования", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 6, "name": "Управление регионального развития", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 7, "name": "Бухгалтерия", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 8, "name": "Управление документального сопровождения проектов", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 9, "name": "Управление внутреннего аудита", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 10, "name": "Финансово-экономическое управление", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 11, "name": "Финансово-экономический отдел", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 12, "name": "Отдел труда и заработной платы", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 13, "name": "Режимно-секретный отдел", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 14, "name": "Управление разработки программного обеспечения", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 15, "name": "Отдел проектирования и разработки архитектуры", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 16, "name": "Отдел обеспечения разработки", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 17, "name": "Отдел разработки прикладного ПО", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 18, "name": "Опытно-исследовательское проектирование", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 19, "name": "Отдел комплексного тестирования", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 20, "name": "Управление разработки и сопровождения коммерческих проектов", "parent_id": None,
     "manager_upn": None, "direction_manager_upn": None},
    {"id": 21, "name": "Отдел разработки программного обеспечения", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 22, "name": "Отдел технической поддержки информационных систем", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 23, "name": "Отдел тестирования и внедрения программного обеспечения", "parent_id": None,
     "manager_upn": None, "direction_manager_upn": None},
    {"id": 24, "name": "Управление научно-технического обеспечения", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 25, "name": "Отдел перспективных информационных технологий", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 26, "name": "Отдел научно-технического сопровождения проектов и работ", "parent_id": None,
     "manager_upn": None, "direction_manager_upn": None},
    {"id": 27, "name": "Отдел защиты интеллектуальной собственности", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 28, "name": "Управление информационной безопасности", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 29, "name": "Управление защищенного документооборота", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 30, "name": "Отдел технического сопровождения и экспертизы", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 31, "name": "Сектор технической экспертизы и взаимодействия с административными органами", "parent_id": None,
     "manager_upn": None, "direction_manager_upn": None},
    {"id": 32, "name": "Сектор поддержки серверов", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 33, "name": "Отдел технической поддержки абонентов", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 34, "name": "Отдел аналитики и методического обеспечения", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 35, "name": "Отдел программного обеспечения", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 36, "name": "Сектор разработки и поддержки веб-технологий", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 37, "name": "Сектор разработки и адаптации ПО", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 38, "name": "Отдел абонентского обслуживания", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 39, "name": "Сектор приёма и подключения абонентов", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 40, "name": "Сектор обработки документов", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 41, "name": "Сектор работы с партнёрами", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 42, "name": "Сектор продления договоров", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 43, "name": "Управление продвижения и продаж", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 44, "name": "Отдел продаж", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 45, "name": "Группа фронт-офис", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 46, "name": "Группа продаж", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 47, "name": "Отдел продвижения", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 48, "name": "Управление специальных работ", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 49, "name": "Управление сопровождения", "parent_id": 49, "manager_upn": "n.orlov@center-inform.ru",
     "direction_manager_upn": None},
    {"id": 50, "name": "Отдел информационно-технического обеспечения", "parent_id": 49,
     "manager_upn": "a.yudin@center-inform.ru", "direction_manager_upn": None},
    {"id": 51, "name": "Отдел материального и хозяйственного обеспечения", "parent_id": None, "manager_upn": None,
     "direction_manager_upn": None},
    {"id": 52, "name": "Водители", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
    {"id": 53, "name": "Группа дежурных", "parent_id": None, "manager_upn": None, "direction_manager_upn": None},
]

EMPLOYEES_DATA = [
    {"user_principal_name": "a.anisimov@center-inform.ru", "display_name": "Анисимов Александр Дмитриевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.antonova@center-inform.ru", "display_name": "Антонова Александра Васильевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.bogdanov@center-inform.ru", "display_name": "Богданов Анатолий Михайлович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.chernenkov@center-inform.ru", "display_name": "Черненков Альберт Александрович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.dankovtseva@center-inform.ru", "display_name": "Данковцева Анастасия Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.ekimov@center-inform.ru", "display_name": "Екимов Андрей Викторович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.esaulov@center-inform.ru", "display_name": "Есаулов Александр Сергеевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.filippova@center-inform.ru", "display_name": "Филиппова Анастасия Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.gerasimov@center-inform.ru", "display_name": "Герасимов Александр Николаевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.grechnevikov@center-inform.ru", "display_name": "Гречневиков Александр Юрьевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.ivanov@center-inform.ru", "display_name": "Иванов Антон Фёдорович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.kalashnikov@center-inform.ru", "display_name": "Калашников Антон Сергеевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.kharlov@center-inform.ru", "display_name": "Харлов Артем Станиславович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.kniazev@center-inform.ru", "display_name": "Князев Антон Олегович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.kokorina@center-inform.ru", "display_name": "Кокорина Анастасия Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.krasnyi@center-inform.ru", "display_name": "Красный Александр Александрович", "department_id": 50, "position_id": 0},
    {"user_principal_name": "a.krylov@center-inform.ru", "display_name": "Крылов Андрей Витальевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.kurtian@center-inform.ru", "display_name": "Куртян Андрей Николаевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.kuzmin@center-inform.ru", "display_name": "Кузьмин Алексей Владимирович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.logaeva@center-inform.ru", "display_name": "Логаева Альфия Хамисовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.miheeva@center-inform.ru", "display_name": "Михеева Анна Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.nagornov@center-inform.ru", "display_name": "Нагорнов Алексей Александрович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.naraev@center-inform.ru", "display_name": "Нараев Александр Вячеславович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.nushtaikin@center-inform.ru", "display_name": "Нуштайкин Алексей Станиславович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.palash@center-inform.ru", "display_name": "Палаш Александр Анатольевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.pavlov@center-inform.ru", "display_name": "Павлов Андрей Николаевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.petrov@center-inform.ru", "display_name": "Петров Артур Валерьевич", "department_id": 50, "position_id": 0},
    {"user_principal_name": "a.plisetskaia@center-inform.ru", "display_name": "Anastasiia V. Plisetskaia", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.romanov@center-inform.ru", "display_name": "Романов Алексей Сергеевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.romanovskaia@center-inform.ru", "display_name": "Романовская Александра Дмитриевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.shakhova@center-inform.ru", "display_name": "Шахова Анастасия Алексеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.sidorova@center-inform.ru", "display_name": "Сидорова Анастасия Анатольевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.starikov@center-inform.ru", "display_name": "Стариков Андрей Олегович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.tetianko@center-inform.ru", "display_name": "Тэтянко Андрей Вадимович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.tsybin@center-inform.ru", "display_name": "Цыбин Александр Анатольевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.vasileva@center-inform.ru", "display_name": "Васильева Альбина Рамильевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.vershinina@center-inform.ru", "display_name": "Вершинина Альбина Викторовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.vikhliantsev@center-inform.ru", "display_name": "Вихлянцев Александр Петрович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.volkov@center-inform.ru", "display_name": "Волков Алексей Сергеевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "a.yudin@center-inform.ru", "display_name": "Юдин Артем Анатольевич", "department_id": 50, "position_id": 0},
    {"user_principal_name": "a.zemko@center-inform.ru", "display_name": "Земко Артём Александрович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "ca_check@center-inform.ru", "display_name": "CA Check", "department_id": 0, "position_id": 0},
    {"user_principal_name": "ci-guest@center-inform.ru", "display_name": "WIFI Guest Portal User", "department_id": 0, "position_id": 0},
    {"user_principal_name": "cucmldap@center-inform.ru", "display_name": "cucmldap", "department_id": 0, "position_id": 0},
    {"user_principal_name": "d.bulygina@center-inform.ru", "display_name": "Булыгина Дарья Андреевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "d.fedosov@center-inform.ru", "display_name": "Федосов Денис Игоревич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "d.gorbunov@center-inform.ru", "display_name": "Горбунов Дмитрий Константинович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "d.novoselov@center-inform.ru", "display_name": "Новосёлов Денис Александрович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "doc@center-inform.ru", "display_name": "DOC", "department_id": 0, "position_id": 0},
    {"user_principal_name": "dogovor@center-inform.ru", "display_name": "Dogovor", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.akimova@center-inform.ru", "display_name": "Акимова Елена Алексеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.ardasheva@center-inform.ru", "display_name": "Ардашева Евгения Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.borodavko@center-inform.ru", "display_name": "Бородавко Евгения Гавриловна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.bushuev@center-inform.ru", "display_name": "Бушуев Евгений Николаевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.gavrilina@center-inform.ru", "display_name": "Гаврилина Екатерина Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.gavrilova@center-inform.ru", "display_name": "Гаврилова Елена Юрьевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.karabanov@center-inform.ru", "display_name": "Карабанов Евгений Сергеевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.kornienko@center-inform.ru", "display_name": "Корниенко Елизавета Витальевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.matveeva@center-inform.ru", "display_name": "Матвеева Екатерина Анатольевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.orlova@center-inform.ru", "display_name": "Орлова Екатерина Николаевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.pavlova@center-inform.ru", "display_name": "Павлова Елена Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.roschupkina@center-inform.ru", "display_name": "Рощупкина Елена Анатольевна", "department_id": 50, "position_id": 0},
    {"user_principal_name": "e.rusakova@center-inform.ru", "display_name": "Русакова Елена Вячеславовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.shmyrin@center-inform.ru", "display_name": "Шмырин Евгений Александрович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.stankevich@center-inform.ru", "display_name": "Станкевич Екатерина Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.tolmacheva@center-inform.ru", "display_name": "Толмачёва Елена Николаевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.vlasov@center-inform.ru", "display_name": "Власов Егор Алексеевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.zaitseva@center-inform.ru", "display_name": "Зайцева Екатерина Леонидовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "e.zhelyazkov@center-inform.ru", "display_name": "Желязков Евгений Иванович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "extest2019@center-inform.ru", "display_name": "extest2019", "department_id": 0, "position_id": 0},
    {"user_principal_name": "g.narygin@center-inform.ru", "display_name": "Нарыгин Григорий Сергеевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.demina@center-inform.ru", "display_name": "Демина Ирина Петровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.dneprovskaia@center-inform.ru", "display_name": "Днепровская Ирина Борисовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.kazantseva@center-inform.ru", "display_name": "Казанцева Ирина Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.kharitonova@center-inform.ru", "display_name": "Харитонова Ирина Андреевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.kharlova@center-inform.ru", "display_name": "Харлова Юлия Всеволодовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.konstantinovskii@center-inform.ru", "display_name": "Константиновский Илья Владимирович", "department_id": 50, "position_id": 0},
    {"user_principal_name": "i.kravtsov_bak@center-inform.ru", "display_name": "Кравцов Иван Павлович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.krush@center-inform.ru", "display_name": "Круш Ирина Викторовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.kuznetsova@center-inform.ru", "display_name": "Кузнецова Ирина Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.liubtsova@center-inform.ru", "display_name": "Любцова Юлия Дмитриевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.parusova@center-inform.ru", "display_name": "Парусова Ирина Михайловна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.ratkov@center-inform.ru", "display_name": "Ратьков Игорь Иванович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.sazanova@center-inform.ru", "display_name": "Сазанова Ирина Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.serbina@center-inform.ru", "display_name": "Сербина Инна Николаевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.shibaeva@center-inform.ru", "display_name": "Шибаева Ярослава Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.sokolova@center-inform.ru", "display_name": "Соколова Ирина Алексеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.trofimtsov@center-inform.ru", "display_name": "Трофимцов Игорь Александрович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.tumashevich@center-inform.ru", "display_name": "Тумашевич Инна Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "i.zhukova@center-inform.ru", "display_name": "Жукова Юлия Вадимовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "imns@center-inform.ru", "display_name": "IMNS", "department_id": 0, "position_id": 0},
    {"user_principal_name": "info@center-inform.ru", "display_name": "АО ЦентрИнформ", "department_id": 0, "position_id": 0},
    {"user_principal_name": "IngridLDAPSearch@center-inform.ru", "display_name": "IngridLDAPSearch", "department_id": 0, "position_id": 0},
    {"user_principal_name": "itsupport@center-inform.ru", "display_name": "Information Technology Support", "department_id": 0, "position_id": 0},
    {"user_principal_name": "j.avramenko@center-inform.ru", "display_name": "Авраменко Юлия Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "j.jabber@center-inform.ru", "display_name": "J J. Jabber", "department_id": 0, "position_id": 0},
    {"user_principal_name": "j.kazhurina@center-inform.ru", "display_name": "Кажурина Юлия Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "j.kostiukova@center-inform.ru", "display_name": "Костюкова Юлия Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "j.vasilevskaia@center-inform.ru", "display_name": "Василевская Яна Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "k.alekseeva@center-inform.ru", "display_name": "Алексеева Кристина Витальевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "k.biriukov@center-inform.ru", "display_name": "Бирюков Константин Александрович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "k.gorbunov@center-inform.ru", "display_name": "Горбунов Константин Дмитриевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "k.iliin@center-inform.ru", "display_name": "Ильин Кирилл Сергеевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "k.illarionov@center-inform.ru", "display_name": "Илларионов Константин Викторович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "k.ivantsov@center-inform.ru", "display_name": "Иванцов Кирилл Михайлович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "k.krassova@center-inform.ru", "display_name": "Крассова Ксения Юрьевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "k.perminov@center-inform.ru", "display_name": "Перминов Константин Васильевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "k.tetianko@center-inform.ru", "display_name": "Тэтянко Кирилл Вадимович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "keeper@center-inform.ru", "display_name": "Keeper", "department_id": 0, "position_id": 0},
    {"user_principal_name": "l.akashkin@center-inform.ru", "display_name": "Акашкин Леонид Анатольевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "l.alekseeva@center-inform.ru", "display_name": "Алексеева Людмила Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "l.serebrianskaia@center-inform.ru", "display_name": "Серебрянская Лада Игоревна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "l.terenteva@center-inform.ru", "display_name": "Терентьева Людмила Ивановна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.ardashev@center-inform.ru", "display_name": "Ардашев Михаил Александрович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.borisenko@center-inform.ru", "display_name": "Борисенко Марина Викторовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.klinova@center-inform.ru", "display_name": "Клинова Марина Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.kosova@center-inform.ru", "display_name": "Косова Марина Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.makarevich@center-inform.ru", "display_name": "Макаревич Мария Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.mitchina@center-inform.ru", "display_name": "Митчина Мария Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.ottas@center-inform.ru", "display_name": "Оттас Маргарита Дмитриевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.polikasheva@center-inform.ru", "display_name": "Поликашева Мария Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.potapova@center-inform.ru", "display_name": "Потапова Марина Анатольевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.rabinovich@center-inform.ru", "display_name": "Рабинович Мария Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.shibaeva@center-inform.ru", "display_name": "Шибаева Мария Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.staroverov@center-inform.ru", "display_name": "Староверов Максим Юрьевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "m.volkov@center-inform.ru", "display_name": "Волков Михаил Юрьевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "meeting@center-inform.ru", "display_name": "АО ЦентрИнформ (Skype for Business)", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.beliaeva@center-inform.ru", "display_name": "Беляева Наталья Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.borisova@center-inform.ru", "display_name": "Борисова Надежда Юрьевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.entin@center-inform.ru", "display_name": "Энтин Николай Семёнович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.kanova@center-inform.ru", "display_name": "Канова Наталья Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.latypova@center-inform.ru", "display_name": "Латыпова Надежда Вениаминовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.lebedeva@center-inform.ru", "display_name": "Лебедева Наталья Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.orlov@center-inform.ru", "display_name": "Орлов Николай Андреевич", "department_id": 49, "position_id": 0},
    {"user_principal_name": "n.serdiukov@center-inform.ru", "display_name": "Сердюков Николай Николаевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.sibul@center-inform.ru", "display_name": "Сибул Николай Андреевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.strashevskii@center-inform.ru", "display_name": "Страшевский Николай Николаевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.tsvetkova@center-inform.ru", "display_name": "Цветкова Наталия Викторовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "n.zaliazhnaia@center-inform.ru", "display_name": "Заляжная Наталья Павловна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.baburin@center-inform.ru", "display_name": "Бабурин Олег Аркадьевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.belousova@center-inform.ru", "display_name": "Белоусова Ольга Аркадьевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.bernatskaia@center-inform.ru", "display_name": "Бернацкая Олеся Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.bratashova@center-inform.ru", "display_name": "Браташова Ольга Николаевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.ekimova@center-inform.ru", "display_name": "Екимова Ольга Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.ignateva@center-inform.ru", "display_name": "Игнатьева Оксана Игоревна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.koroleva@center-inform.ru", "display_name": "Королева Оксана Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.liakhova@center-inform.ru", "display_name": "Ляхова Ольга Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.mikhailova@center-inform.ru", "display_name": "Михайлова Ольга Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.morozova@center-inform.ru", "display_name": "Морозова Ольга Евгеньевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.rezakova@center-inform.ru", "display_name": "Резакова Ольга Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.veselova@center-inform.ru", "display_name": "Веселова Ольга Васильевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "o.vovk@center-inform.ru", "display_name": "Вовк Ольга Анатольевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "oplata@center-inform.ru", "display_name": "Oplata", "department_id": 0, "position_id": 0},
    {"user_principal_name": "p.gusev@center-inform.ru", "display_name": "Гусев Павел Михайлович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "p.postnikov@center-inform.ru", "display_name": "Постников Павел Валерьевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "p.vikhliantsev@center-inform.ru", "display_name": "Вихлянцев Пётр Сергеевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "partner@center-inform.ru", "display_name": "Partner Sector", "department_id": 0, "position_id": 0},
    {"user_principal_name": "personal@center-inform.ru", "display_name": "Управление по работе с персоналом", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.anisimova@center-inform.ru", "display_name": "Анисимова Светлана Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.basova@center-inform.ru", "display_name": "Басова Светлана Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.beletskaia@center-inform.ru", "display_name": "Белецкая Светлана Леонидовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.dobrokhotov@center-inform.ru", "display_name": "Доброхотов Сергей Геннадьевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.dyachkov@center-inform.ru", "display_name": "Дьячков Сергей Геннадьевич", "department_id": 50, "position_id": 0},
    {"user_principal_name": "s.ignatev@center-inform.ru", "display_name": "Игнатьев Сергей Владимирович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.izotov@center-inform.ru", "display_name": "Изотов Сергей Валентинович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.kazancev@center-inform.ru", "display_name": "Казанцев Сергей Владимирович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.komlev@center-inform.ru", "display_name": "Комлев Сергей Игоревич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.matveeva@center-inform.ru", "display_name": "Матвеева Светлана Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.mosin@center-inform.ru", "display_name": "Мосин Сергей Анатольевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.ostrogliadov@center-inform.ru", "display_name": "Остроглядов Сергей Дмитриевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.savenko@center-inform.ru", "display_name": "Савенко Станислав Викторович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.shulumei@center-inform.ru", "display_name": "Шулумей Сергей Александрович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "s.suhanov@center-inform.ru", "display_name": "Суханов Сергей Николаевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "sam@center-inform.ru", "display_name": "SAM", "department_id": 0, "position_id": 0},
    {"user_principal_name": "spam@center-inform.ru", "display_name": "Anti-Spam Quarantine", "department_id": 0, "position_id": 0},
    {"user_principal_name": "sps@center-inform.ru", "display_name": "Сектор поддержки серверов", "department_id": 0, "position_id": 0},
    {"user_principal_name": "support@center-inform.ru", "display_name": "Отдел ИТО", "department_id": 0, "position_id": 0},
    {"user_principal_name": "t.efimova@center-inform.ru", "display_name": "Ефимова Татьяна Алексеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "t.kirikova@center-inform.ru", "display_name": "Кирикова Татьяна Анатольевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "t.nekrasova@center-inform.ru", "display_name": "Некрасова Татьяна Михайловна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "t.noskova@center-inform.ru", "display_name": "Носкова Татьяна Николаевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "t.nurtdinov@center-inform.ru", "display_name": "Нуртдинов Тимур Наилевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "t.peshkova@center-inform.ru", "display_name": "Пешкова Татьяна Анатольевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "t.pokudova@center-inform.ru", "display_name": "Покудова Татьяна Викторовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "t.pozdniakova@center-inform.ru", "display_name": "Позднякова Татьяна Леонидовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "t.streltsova@center-inform.ru", "display_name": "Стрельцова Татьяна Валентиновна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "t.suhanova@center-inform.ru", "display_name": "Суханова Татьяна Сергеевна", "department_id": 49, "position_id": 0},
    {"user_principal_name": "tehpo2@center-inform.ru", "display_name": "Tehpo2", "department_id": 0, "position_id": 0},
    {"user_principal_name": "torgi@center-inform.ru", "display_name": "Торги АО ЦентрИнформ", "department_id": 0, "position_id": 0},
    {"user_principal_name": "usr@center-inform.ru", "display_name": "Управление специальных работ", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.bogdanov@center-inform.ru", "display_name": "Богданов Владимир Николаевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.koltsova@center-inform.ru", "display_name": "Кольцова Валентина Валерьевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.kovrigina@center-inform.ru", "display_name": "Ковригина Вера Дмитриевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.martynova@center-inform.ru", "display_name": "Мартынова Вера Юрьевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.mirzakulova@center-inform.ru", "display_name": "Мирзакулова Валерия Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.mshar@center-inform.ru", "display_name": "Мшар Вадим Васильевич", "department_id": 50, "position_id": 0},
    {"user_principal_name": "v.nekh@center-inform.ru", "display_name": "Нех Валерия Владимировна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.ofitserov@center-inform.ru", "display_name": "Офицеров Владислав Николаевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.pokhodin@center-inform.ru", "display_name": "Походин Виктор Дмитриевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.shamkina@center-inform.ru", "display_name": "Шамкина Вера Александровна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.shatalin@center-inform.ru", "display_name": "Шаталин Василий Андреевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.shelukhin@center-inform.ru", "display_name": "Шелухин Владимир Николаевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.skrebneva@center-inform.ru", "display_name": "Скребнева Виктория Сергеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.sokolov@center-inform.ru", "display_name": "Соколов Владимир Геннадьевич", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.tishchenko@center-inform.ru", "display_name": "Тищенко Владимир Владимирович", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.yaroshevich@center-inform.ru", "display_name": "Ярошевич Валерия Вадимовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "v.zakharova@center-inform.ru", "display_name": "Захарова Виктория Алексеевна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "voditeli@center-inform.ru", "display_name": "Водители", "department_id": 0, "position_id": 0},
    {"user_principal_name": "web@center-inform.ru", "display_name": "Сектор разработки и поддержки web-технологий", "department_id": 0, "position_id": 0},
    {"user_principal_name": "z.nikolaeva@center-inform.ru", "display_name": "Николаева Жанна Борисовна", "department_id": 0, "position_id": 0},
    {"user_principal_name": "zakupki@center-inform.ru", "display_name": "Закупки АО ЦентрИнформ", "department_id": 0, "position_id": 0},
    {"user_principal_name": "zapros@center-inform.ru", "display_name": "Zapros", "department_id": 0, "position_id": 0},
]

async def import_data():
    async with AsyncSessionLocal() as session:
        try:
            # Импортируем позиции
            for data in POSITIONS_DATA:
                obj = Position(**data)
                await session.merge(obj)  # merge = insert or update

            # Импортируем отделы
            for data in DEPARTMENTS_DATA:
                obj = Department(**data)
                await session.merge(obj)

            # Импортируем сотрудников
            for data in EMPLOYEES_DATA:
                obj = Employee(**data)
                await session.merge(obj)

            # ← НОВОЕ: Заполняем EmployeeCard
            for emp_data in EMPLOYEES_DATA:
                upn = emp_data["user_principal_name"]
                # Если user_principal_name == "1" — возможно, это заглушка, пропускаем?
                if upn == "1":
                    continue  # ← опционально: пропустить нереальные UPN
                card_record = EmployeeCard(
                    employee_upn=upn,
                    card_id=287  # ← или None, если нужно NULL
                )
                await session.merge(card_record)  # merge безопасен при дублях

            await session.commit()
            print("✅ Данные успешно импортированы")

        except IntegrityError as e:
            await session.rollback()
            print("❌ Ошибка целостности:", e)
        except Exception as e:
            await session.rollback()
            print("❌ Ошибка:", e)

if __name__ == "__main__":
    # Создать таблицы, если не существуют
    # Base.metadata.create_all(engine)
    asyncio.run(import_data())