import asyncio

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.exc import IntegrityError
from db.database import engine, Base, AsyncSessionLocal
from models import Position, Department, Employee  # ← Замените на путь к вашим моделям

# Данные для импорта
POSITIONS_DATA = [
    {"id": 0, "name": "Не задана"},
    {"id": 26, "name": "Разработчик"},
    {"id": 28, "name": "Руководитель отдела"},
    {"id": 31, "name": "Специалист техподдержки"},
    {"id": 34, "name": "Менеджер"},
    # Добавьте остальные, если нужно
]

DEPARTMENTS_DATA = [
    {"id": 0, "name": "Не задан", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 1, "name": "Руководство", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 2, "name": "Архив", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 3, "name": "Управление по работе с персоналом", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 4, "name": "Юридический отдел", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 5, "name": "Отдел лицензирования", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 6, "name": "Управление регионального развития", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 7, "name": "Бухгалтерия", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 8, "name": "Управление документального сопровождения проектов", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 9, "name": "Управление внутреннего аудита", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 10, "name": "Финансово-экономическое управление", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 11, "name": "Финансово-экономический отдел", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 12, "name": "Отдел труда и заработной платы", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 13, "name": "Режимно-секретный отдел", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 14, "name": "Управление разработки программного обеспечения", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 15, "name": "Отдел проектирования и разработки архитектуры", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 16, "name": "Отдел обеспечения разработки", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 17, "name": "Отдел разработки прикладного ПО", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 18, "name": "Опытно-исследовательское проектирование", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 19, "name": "Отдел комплексного тестирования", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 20, "name": "Управление разработки и сопровождения коммерческих проектов", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 21, "name": "Отдел разработки программного обеспечения", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 22, "name": "Отдел технической поддержки информационных систем", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 23, "name": "Отдел тестирования и внедрения программного обеспечения", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 24, "name": "Управление научно-технического обеспечения", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 25, "name": "Отдел перспективных информационных технологий", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 26, "name": "Отдел научно-технического сопровождения проектов и работ", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 27, "name": "Отдел защиты интеллектуальной собственности", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 28, "name": "Управление информационной безопасности", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 29, "name": "Управление защищенного документооборота", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 30, "name": "Отдел технического сопровождения и экспертизы", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 31, "name": "Сектор технической экспертизы и взаимодействия с административными органами", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 32, "name": "Сектор поддержки серверов", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 33, "name": "Отдел технической поддержки абонентов", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 34, "name": "Отдел аналитики и методического обеспечения", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 35, "name": "Отдел программного обеспечения", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 36, "name": "Сектор разработки и поддержки веб-технологий", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 37, "name": "Сектор разработки и адаптации ПО", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 38, "name": "Отдел абонентского обслуживания", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 39, "name": "Сектор приёма и подключения абонентов", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 40, "name": "Сектор обработки документов", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 41, "name": "Сектор работы с партнёрами", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 42, "name": "Сектор продления договоров", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 43, "name": "Управление продвижения и продаж", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 44, "name": "Отдел продаж", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 45, "name": "Группа фронт-офис", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 46, "name": "Группа продаж", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 47, "name": "Отдел продвижения", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 48, "name": "Управление специальных работ", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 49, "name": "Управление сопровождения", "parent_id": None, "manager_id": 118, "direction_manager_id": None},
    {"id": 50, "name": "Отдел информационно-технического обеспечения", "parent_id": 49, "manager_id": 180, "direction_manager_id": 127},
    {"id": 51, "name": "Отдел материального и хозяйственного обеспечения", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 52, "name": "Водители", "parent_id": None, "manager_id": None, "direction_manager_id": None},
    {"id": 53, "name": "Группа дежурных", "parent_id": None, "manager_id": None, "direction_manager_id": None},
]

EMPLOYEES_DATA = [
    {"id": 1, "display_name": "Акашкин Леонид Анатольевич", "user_principal_name": "l.akashkin@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 2, "display_name": "Акимова Елена Алексеевна", "user_principal_name": "e.akimova@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 3, "display_name": "Алексеева Кристина Витальевна", "user_principal_name": "k.alekseeva@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 4, "display_name": "Алексеева Людмила Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 5, "display_name": "Анисимова Светлана Александровна", "user_principal_name": "s.anisimova@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 6, "display_name": "Антонова Александра Васильевна", "user_principal_name": "a.antonova@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 7, "display_name": "Ардашев Михаил Александрович", "user_principal_name": "m.ardashev@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 8, "display_name": "Ардашева Евгения Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 9, "display_name": "Арестов Андрей Анатольевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 10, "display_name": "Бабурин Олег Аркадьевич", "user_principal_name": "o.baburin@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 11, "display_name": "Басова Светлана Сергеевна", "user_principal_name": "s.basova@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 12, "display_name": "Белецкая Светлана Леонидовна", "user_principal_name": "s.beletckaya@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 13, "display_name": "Белоусова Ольга Аркадьевна", "user_principal_name": "o.belousova@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 14, "display_name": "Беляева Наталья Сергеевна", "user_principal_name": "n.belayeva@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 15, "display_name": "Бернацкая Олеся Сергеевна", "user_principal_name": "o.bernatskaia@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 16, "display_name": "Бирюков Константин Александрович", "user_principal_name": "k.biriukov@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 17, "display_name": "Бламар Ирина Олеговна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 18, "display_name": "Богданов Анатолий Михайлович", "user_principal_name": "a.bogdanov@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 19, "display_name": "Богданов Владимир Николаевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 20, "display_name": "Богданова Людмила Михайловна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 21, "display_name": "Борисова Надежда Юрьевна", "user_principal_name": "n.borisova@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 22, "display_name": "Бородавко Евгения Гавриловна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 23, "display_name": "Браташова Ольга Николаевна", "user_principal_name": "o.bratashova@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 24, "display_name": "Буйдылло Артем Сергеевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 25, "display_name": "Булыгина Дарья Андреевна", "user_principal_name": "d.bulygina@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 26, "display_name": "Бушуев Евгений Николаевич", "user_principal_name": "e.bushuev@center-inform.ru", "department_id": 0, "position_id": 0},
    {"id": 27, "display_name": "Василевская Яна Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 28, "display_name": "Васильева Альбина Рамильевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 29, "display_name": "Вершинина Альбина Викторовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 30, "display_name": "Веселова Карина Леонидовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 31, "display_name": "Веселова Ольга Васильевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 32, "display_name": "Вихлянцев Александр Петрович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 33, "display_name": "Вихлянцев Петр Сергеевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 34, "display_name": "Власов Егор Алексеевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 35, "display_name": "Вовк Ольга Анатольевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 36, "display_name": "Волков Алексей Сергеевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 37, "display_name": "Волков Михаил Юрьевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 38, "display_name": "Горбунов Дмитрий Константинович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 39, "display_name": "Гречневиков Александр Юрьевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 40, "display_name": "Гусев Павел Михайлович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 41, "display_name": "Данковцева Анастасия Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 42, "display_name": "Демина Ирина Петровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 43, "display_name": "Денисов Александр Евгеньевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 44, "display_name": "Днепровская Ирина Борисовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 45, "display_name": "Доброхотов Сергей Геннадьевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 46, "display_name": "Дьячков Сергей Геннадьевич", "user_principal_name": "1", "department_id": 50, "position_id": 0},
    {"id": 47, "display_name": "Екимов Андрей Викторович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 48, "display_name": "Екимова Ольга Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 49, "display_name": "Есаулов Александр Сергеевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 50, "display_name": "Ефимов Андрей Анатольевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 51, "display_name": "Ефимова Татьяна Алексеевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 52, "display_name": "Желязков Евгений Иванович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 53, "display_name": "Жукова Юлия Вадимовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 54, "display_name": "Загвоздкин Александр Борисович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 55, "display_name": "Зайцева Екатерина Леонидовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 56, "display_name": "Заляжная Наталья Павловна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 57, "display_name": "Захарова Виктория Алексеевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 58, "display_name": "Земко Артем Александрович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 59, "display_name": "Иванов Антон Федорович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 60, "display_name": "Игнатьев Сергей Владимирович", "user_principal_name": "s.ignatev@center-inform.ru", "department_id": 29, "position_id": 28},
    {"id": 61, "display_name": "Игнатьева Оксана Игоревна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 62, "display_name": "Изотов Сергей Валентинович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 63, "display_name": "Илларионов Константин Викторович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 64, "display_name": "Кажурина Юлия Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 65, "display_name": "Казанцев Владимир Анатольевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 66, "display_name": "Казанцева Ирина Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 67, "display_name": "Калашников Антон Сергеевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 68, "display_name": "Калинина Эльмира Фатиховна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 69, "display_name": "Канова Наталья Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 70, "display_name": "Карабанов Евгений Сергеевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 71, "display_name": "Кирикова Татьяна Анатольевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 72, "display_name": "Клинова Марина Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 73, "display_name": "Князев Антон Олегович", "user_principal_name": "a.kniazev@center-inform.ru", "department_id": 33, "position_id": 31},
    {"id": 74, "display_name": "Кобякова Анна Альбертовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 75, "display_name": "Ковригина Вера Дмитриевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 76, "display_name": "Козырев Александр Владимирович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 77, "display_name": "Кокорина Анастасия Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 78, "display_name": "Колпаков Максим Олегович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 79, "display_name": "Кольцова Валентина Валерьевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 80, "display_name": "Комлев Сергей Игоревич", "user_principal_name": "s.komlev@center-inform.ru", "department_id": 17, "position_id": 26},
    {"id": 81, "display_name": "Королева Оксана Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 82, "display_name": "Косова Марина Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 83, "display_name": "Костыгина Арина Андреевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 84, "display_name": "Костюкова Юлия Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 85, "display_name": "Кравцов Иван Павлович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 86, "display_name": "Красный Александр Александрович", "user_principal_name": "1", "department_id": 50, "position_id": 0},
    {"id": 87, "display_name": "Круш Ирина Викторовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 88, "display_name": "Крылов Андрей Витальевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 89, "display_name": "Кузнецова Ирина Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 90, "display_name": "Кузьмин Алексей Владимирович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 91, "display_name": "Куртян Андрей Николаевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 92, "display_name": "Латыпова Надежда Вениаминовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 93, "display_name": "Лебедева Наталья Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 94, "display_name": "Леминов Сергей Моисеевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 95, "display_name": "Лобанов Михаил Дмитриевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 96, "display_name": "Лобачев Андрей Борисович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 97, "display_name": "Логаева Альфия Хамисовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 98, "display_name": "Любцова Юлия Дмитриевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 99, "display_name": "Ляхова Ольга Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 100, "display_name": "Макаревич Мария Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 101, "display_name": "Мартынова Вера Юрьевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 102, "display_name": "Матвеева Екатерина Анатольевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 103, "display_name": "Медведев Виктор Алексеевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 104, "display_name": "Михайлова Ольга Сергеевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 105, "display_name": "Морозов Максим Николаевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 106, "display_name": "Морозова Ольга Евгеньевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 107, "display_name": "Мосин Сергей Анатольевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 108, "display_name": "Мосина Наталья Викторовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 109, "display_name": "Муратова Виктория Владиславовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 110, "display_name": "Мшар Вадим Васильевич", "user_principal_name": "1", "department_id": 50, "position_id": 0},
    {"id": 111, "display_name": "Нагорнов Алексей Александрович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 112, "display_name": "Некрасова Татьяна Михайловна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 113, "display_name": "Николаева Жанна Борисовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 114, "display_name": "Новоселов Денис Александрович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 115, "display_name": "Носкова Татьяна Николаевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 116, "display_name": "Нуртдинов Тимур Наилевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 117, "display_name": "Обухов Виталий Анатольевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 118, "display_name": "Орлов Николай Андреевич", "user_principal_name": "n.orlov@center-inform.ru", "department_id": 49, "position_id": 28},
    {"id": 119, "display_name": "Орлова Екатерина Николаевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 120, "display_name": "Остроглядов Сергей Дмитриевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 121, "display_name": "Офицеров Владислав Николаевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 122, "display_name": "Павлов Андрей Николаевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 123, "display_name": "Павлова Елена Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 124, "display_name": "Павлюкович Мария Вячеславовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 125, "display_name": "Палаш Александр Анатольевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 126, "display_name": "Парусова Ирина Михайловна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 127, "display_name": "Перминов Константин Васильевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 128, "display_name": "Перминова Татьяна Константиновна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 129, "display_name": "Петров Артур Валерьевич", "user_principal_name": "1", "department_id": 50, "position_id": 0},
    {"id": 130, "display_name": "Пешкова Татьяна Анатольевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 131, "display_name": "Позднякова Татьяна Леонидовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 132, "display_name": "Покудова Татьяна Викторовна", "user_principal_name": "t.pokudova@center-inform.ru", "department_id": 3, "position_id": 28},
    {"id": 133, "display_name": "Поликашева Мария Сергеевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 134, "display_name": "Постников Павел Валерьевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 135, "display_name": "Потапова Марина Анатольевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 136, "display_name": "Походин Виктор Дмитриевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 137, "display_name": "Ратьков Игорь Иванович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 138, "display_name": "Резакова Ольга Сергеевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 139, "display_name": "Романов Алексей Сергеевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 140, "display_name": "Рощупкина Елена Анатольевна", "user_principal_name": "1", "department_id": 50, "position_id": 0},
    {"id": 141, "display_name": "Русакова Елена Вячеславовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 142, "display_name": "Савенко Станислав Викторович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 143, "display_name": "Сазанова Ирина Сергеевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 144, "display_name": "Светловидова Рената Амировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 145, "display_name": "Сербина Инна Николаевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 146, "display_name": "Сердюков Николай Николаевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 147, "display_name": "Сибул Николай Андреевич", "user_principal_name": "1", "department_id": 33, "position_id": 0},
    {"id": 148, "display_name": "Симонов Михаил Владимирович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 149, "display_name": "Соколов Владимир Геннадьевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 150, "display_name": "Соколова Ирина Алексеевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 151, "display_name": "Станкевич Екатерина Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 152, "display_name": "Староверов Максим Юрьевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 153, "display_name": "Страшевский Николай Николаевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 154, "display_name": "Стрельцова Татьяна Валентиновна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 155, "display_name": "Суханов Сергей Николаевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 156, "display_name": "Суханова Татьяна Сергеевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 157, "display_name": "Терентьева Людмила Ивановна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 158, "display_name": "Тищенко Владимир Владимирович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 159, "display_name": "Толмачев Максим Вячеславович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 160, "display_name": "Толмачева Елена Николаевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 161, "display_name": "Торопская Марина Аркадьевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 162, "display_name": "Трофимцов Игорь Александрович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 163, "display_name": "Тумашевич Инна Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 164, "display_name": "Тэтянко Андрей Вадимович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 165, "display_name": "Тэтянко Кирилл Вадимович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 166, "display_name": "Федосов Денис Игоревич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 167, "display_name": "Филиппова Анастасия Владимировна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 168, "display_name": "Харитонова Ирина Андреевна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 169, "display_name": "Харлова Юлия Всеволодовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 170, "display_name": "Цветкова Наталия Викторовна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 171, "display_name": "Цыбин Александр Анатольевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 172, "display_name": "Черненков Альберт Александрович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 173, "display_name": "Шамкина Вера Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 174, "display_name": "Шаталин Василий Андреевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 175, "display_name": "Шаховцев Владимир Витальевич", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 176, "display_name": "Шибаева Мария Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 177, "display_name": "Шмакова Варвара Александровна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 178, "display_name": "Щербинина Екатерина Олеговна", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 179, "display_name": "Энтин Николай Семенович", "user_principal_name": "1", "department_id": 0, "position_id": 0},
    {"id": 180, "display_name": "Юдин Артем Анатольевич", "user_principal_name": "a.yudin@center-inform.ru", "department_id": 50, "position_id": 26},
    {"id": 181, "display_name": "Ярошевич Валерия Вадимовна", "user_principal_name": "v.yaroshevich@center-inform.ru", "department_id": 44, "position_id": 26},
    {"id": 182, "display_name": "Гаврилова Елена Юрьевна", "user_principal_name": "e.gavrilova@center-inform.ru", "department_id": 0, "position_id": 0},
]

async def import_data():
    async with AsyncSessionLocal() as session:
        try:
            # Импортируем позиции
            for data in POSITIONS_DATA:
                obj = Position(**data)
                await session.merge(obj)  # merge = insert or update

            # Импортируем отделы
            for data in DEPARTMENTS_DATA:
                obj = Department(**data)
                await session.merge(obj)

            # Импортируем сотрудников
            for data in EMPLOYEES_DATA:
                obj = Employee(**data)
                await session.merge(obj)

            await session.commit()
            print("✅ Данные успешно импортированы")

        except IntegrityError as e:
            await session.rollback()
            print("❌ Ошибка целостности:", e)
        except Exception as e:
            await session.rollback()
            print("❌ Ошибка:", e)

if __name__ == "__main__":
    # Создать таблицы, если не существуют
    # Base.metadata.create_all(engine)
    asyncio.run(import_data())